"""Data models used across the SIEM platform."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional


@dataclass
class Event:
    """Normalized event generated from raw log data."""

    timestamp: datetime
    source: str
    category: str
    severity: str
    details: Dict[str, str]


@dataclass
class Alert:
    """Alert generated by detection rules."""

    id: str
    created_at: datetime
    title: str
    description: str
    priority: str
    events: List[Event] = field(default_factory=list)
    remediation: Optional[str] = None


@dataclass
class DetectionRule:
    """Configuration for a detection rule."""

    id: str
    name: str
    rule_type: str
    description: str
    severity: str
    enabled: bool
    parameters: Dict[str, str]
    remediation: Optional[str] = None
